/* The channel tables. Generated by pinside from the fixture config -- do not edit.
 *
 * fixture:    kilncontrol-fixture
 * target:     rp2350b
 * DUT board:  /Users/bernhardtrinnes/Developer/Bitcrush/kilncontrol/hardware/kilncontrol.kicad_pcb
 * config:     3db150410419
 */

#include "fixture_config.h"

#include "fixture_hal.h"

const char fx_fixture_name[] = "kilncontrol-fixture";
const char fx_fixture_version[] = "0.2.0";
const char fx_target_mcu[] = "rp2350b";
const char fx_dut_board[] = "/Users/bernhardtrinnes/Developer/Bitcrush/kilncontrol/hardware/kilncontrol.kicad_pcb";
const char fx_config_hash[] = "3db150410419";
const uint32_t fx_clock_hz = 150000000u;

const fx_gpio_desc fx_gpio[] = {
    {"tc1_cs", "TC1_CS", "TC1_CS -- DUT output: the controller drives chip select. Mastering this bus from the fixture requires the DUT held in reset via ESP32_EN first, and is not configured here", 6, FX_DIR_INPUT, FX_PULL_NONE, false, false},
    {"tc1_drdy", "TC1_DRDY", "TC1_DRDY -- front-end output: MAX31856 data-ready", 7, FX_DIR_INPUT, FX_PULL_NONE, false, false},
    {"tc1_fault", "TC1_FAULT", "TC1_FAULT -- front-end output: MAX31856 ~FAULT. Already an input in the draft, and correct", 8, FX_DIR_INPUT, FX_PULL_NONE, false, false},
    {"ssr1", "SSR1", "SSR1 -- DUT output: SSR gate drive from the controller", 9, FX_DIR_INPUT, FX_PULL_NONE, false, false},
    {"heat_en", "HEAT_EN", "HEAT_EN -- DUT output: the charge-pump square wave (SYS-SAF-02)", 10, FX_DIR_INPUT, FX_PULL_NONE, false, false},
    {"pump_node", "PUMP_NODE", "PUMP_NODE -- DUT output: charge-pump node, and analogue rather than logic", 11, FX_DIR_INPUT, FX_PULL_NONE, false, false},
    {"heat_en_dc", "HEAT_EN_DC", "HEAT_EN_DC -- DUT output: the rectified charge-pump rail, analogue", 12, FX_DIR_INPUT, FX_PULL_NONE, false, false},
    {"coil_drv", "COIL_DRV", "COIL_DRV -- DUT output: contactor coil drive", 13, FX_DIR_INPUT, FX_PULL_NONE, false, false},
    {"alarm", "ALARM", "ALARM -- DUT output: buzzer drive", 14, FX_DIR_INPUT, FX_PULL_NONE, false, false},
    {"enc_a", "ENC_A", "ENC_A -- DUT input: encoder channel A, simulated by the fixture", 15, FX_DIR_OPEN_DRAIN, FX_PULL_NONE, true, false},
    {"enc_b", "ENC_B", "ENC_B -- DUT input: encoder channel B, simulated by the fixture", 16, FX_DIR_OPEN_DRAIN, FX_PULL_NONE, true, false},
    {"enc_btn", "ENC_BTN", "ENC_BTN -- DUT input: encoder push button", 17, FX_DIR_OPEN_DRAIN, FX_PULL_NONE, true, false},
    {"tc1_p", "TC1_P", "TC1_P -- thermocouple input, millivolts. NEVER driven. Injecting a temperature needs a calibrated mV source the fixture does not have; the probe is placed so one can be added", 18, FX_DIR_INPUT, FX_PULL_NONE, false, false},
    {"tc1_n", "TC1_N", "TC1_N -- thermocouple input, millivolts. NEVER driven, as TC1_P", 19, FX_DIR_INPUT, FX_PULL_NONE, false, false},
    {"curr_sense", "CURR_SENSE", "CURR_SENSE -- CT conditioning output, analogue. Should become an ADC channel once the divider scale is taken from the schematic; left as an observed input rather than inventing a scale", 20, FX_DIR_INPUT, FX_PULL_NONE, false, false},
    {"esp32_en", "ESP32_EN", "ESP32_EN -- DUT input: controller reset, active low", 21, FX_DIR_OPEN_DRAIN, FX_PULL_NONE, true, false},
    {"esp32_io0", "ESP32_IO0", "ESP32_IO0 -- DUT input: controller boot strap, active low", 22, FX_DIR_OPEN_DRAIN, FX_PULL_NONE, true, false},
    {"coil_permit", "COIL_PERMIT", "COIL_PERMIT -- DUT output: the supervisor's permit line (SWR-SAF-38)", 23, FX_DIR_INPUT, FX_PULL_NONE, false, false},
    {"supervisor_reset", "SUPERVISOR_RESET", "SUPERVISOR_RESET -- DUT input: supervisor reset, active low", 24, FX_DIR_OPEN_DRAIN, FX_PULL_NONE, true, false},
};
const size_t fx_gpio_count = 19;

const fx_adc_desc fx_adc[] = {
    {"ch_5v", "+5V", "+5V rail, through a 2:1 divider", 40, 0, 2000, 3300, 165},
    {"ch_3_3v", "+3.3V", "+3.3V rail, through a 2:1 divider", 41, 1, 2000, 3300, 165},
};
const size_t fx_adc_count = 2;

const fx_uart_desc fx_uart[] = {
    {"supervisor_uart", "SUPERVISOR serial link", "rx=SUPERVISOR_TX", 0, 115200u, 8, 1, FX_PARITY_NONE, true, -1, FX_PIN_NONE, 1, FX_PIN_NONE, FX_PIN_NONE},
};
const size_t fx_uart_count = 1;

const fx_i2c_desc fx_i2c[] = {
    {"i2c_i2c", "I2C two-wire bus", "scl=I2C_SCL sda=I2C_SDA", 0, 400000u, false, -1, 0, 5},
};
const size_t fx_i2c_count = 1;

const fx_spi_desc fx_spi[] = {
    {"spi_spi", "SPI SPI bus", "rx=SPI_MISO sck=SPI_SCK tx=SPI_MOSI", 0, 1000000u, 0, FX_ROLE_MASTER, -1, 4, FX_PIN_NONE, 2, 3},
};
const size_t fx_spi_count = 1;

